backend:
  name: github
  repo: ibragimof/blog # <--- IMPORTANT: Replace with your actual GitHub repo!
  branch: main # Or master, depending on your default branch
  base_url: https://auth.saytim.uz # This will be set up with Netlify later
  auth_endpoint: /.netlify/functions/auth # This will be set up with Netlify later

media_folder: "static/uploads" # Folder where uploaded files will be stored relative to site root
public_folder: "/uploads" # The public path for uploaded files

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}